### ISSUE TITLE
CQC suppression suggestion

### ISSUE THREAD

**Issue by Cyruz143** [kami-/admiral#46]
Noticed in A3 a lot at the moment that we're suppressing CQC units and they're leaving their positions, this doesn't happen in A2.

I actually quite like this feature as they roam around and fuck shit up but not sure on the general consensus as mission makers might want them to stay where they are!

Can be disabled using the following: https://community.bistudio.com/wiki/disableAI

**Comment by Winter259** [comment]
Don't we provide the alternative via our inhouse sentry script? If you want
AI to stick to a position such as an FOB you can use sentry units.

**Comment by Cyruz143** [comment]
There two different things, sentry is used to cover gaps that CQC doesn't fill. I'm pretty happy as it is now, just throwing this out here for options.

**Comment by Satire-** [comment]
I'd leave as is, since abandoning positions (Sensibly & when under fire) is adding a dynamic that's going to be hard to replicate via other means. Makes for interesting gameplay.

That said, I'd be fine with making 'hold at all costs' an option per zone, for situations where you want them to stay put (e.g. Bunker on an itherwise empty hil). Flexibility is always good.

**Comment by Cyruz143** [comment]
Agreed Satire, like on Takistan we engaged a guy on balcony and he ran inside the house. Closing down, just thought it was a good idea to check with everyone.
